// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EpisodesColumns holds the columns for the "episodes" table.
	EpisodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 2147483647, Default: "gen_random_ulid()"},
		{Name: "created_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updated_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "title", Type: field.TypeString, Size: 2147483647},
		{Name: "summary", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "picture", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "content", Type: field.TypeJSON, Nullable: true},
		{Name: "show_episodes", Type: field.TypeString, Nullable: true, Size: 2147483647},
	}
	// EpisodesTable holds the schema information for the "episodes" table.
	EpisodesTable = &schema.Table{
		Name:       "episodes",
		Columns:    EpisodesColumns,
		PrimaryKey: []*schema.Column{EpisodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "episodes_shows_episodes",
				Columns:    []*schema.Column{EpisodesColumns[7]},
				RefColumns: []*schema.Column{ShowsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ProfilesColumns holds the columns for the "profiles" table.
	ProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 2147483647, Default: "gen_random_ulid()"},
		{Name: "created_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updated_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "email", Type: field.TypeString, Size: 2147483647},
		{Name: "display_name", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "picture", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "content", Type: field.TypeJSON, Nullable: true},
	}
	// ProfilesTable holds the schema information for the "profiles" table.
	ProfilesTable = &schema.Table{
		Name:       "profiles",
		Columns:    ProfilesColumns,
		PrimaryKey: []*schema.Column{ProfilesColumns[0]},
	}
	// ShowsColumns holds the columns for the "shows" table.
	ShowsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 2147483647, Default: "gen_random_ulid()"},
		{Name: "created_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updated_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "title", Type: field.TypeString, Size: 2147483647},
		{Name: "summary", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "picture", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "content", Type: field.TypeJSON, Nullable: true},
	}
	// ShowsTable holds the schema information for the "shows" table.
	ShowsTable = &schema.Table{
		Name:       "shows",
		Columns:    ShowsColumns,
		PrimaryKey: []*schema.Column{ShowsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 2147483647, Default: "gen_random_ulid()"},
		{Name: "created_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updated_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "username", Type: field.TypeString, Size: 2147483647},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EpisodesTable,
		ProfilesTable,
		ShowsTable,
		UsersTable,
	}
)

func init() {
	EpisodesTable.ForeignKeys[0].RefTable = ShowsTable
}
