// Code generated by entc, DO NOT EDIT.

package ent

import (
	"caster/ent/episode"
	"caster/ent/profile"
	"caster/ent/schema"
	"caster/ent/show"
	"caster/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	episodeFields := schema.Episode{}.Fields()
	_ = episodeFields
	// episodeDescCreatedAt is the schema descriptor for created_at field.
	episodeDescCreatedAt := episodeFields[1].Descriptor()
	// episode.DefaultCreatedAt holds the default value on creation for the created_at field.
	episode.DefaultCreatedAt = episodeDescCreatedAt.Default.(func() time.Time)
	// episodeDescUpdatedAt is the schema descriptor for updated_at field.
	episodeDescUpdatedAt := episodeFields[2].Descriptor()
	// episode.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	episode.DefaultUpdatedAt = episodeDescUpdatedAt.Default.(func() time.Time)
	// episodeDescTitle is the schema descriptor for title field.
	episodeDescTitle := episodeFields[3].Descriptor()
	// episode.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	episode.TitleValidator = episodeDescTitle.Validators[0].(func(string) error)
	// episodeDescSummary is the schema descriptor for summary field.
	episodeDescSummary := episodeFields[4].Descriptor()
	// episode.SummaryValidator is a validator for the "summary" field. It is called by the builders before save.
	episode.SummaryValidator = episodeDescSummary.Validators[0].(func(string) error)
	// episodeDescPicture is the schema descriptor for picture field.
	episodeDescPicture := episodeFields[5].Descriptor()
	// episode.PictureValidator is a validator for the "picture" field. It is called by the builders before save.
	episode.PictureValidator = episodeDescPicture.Validators[0].(func(string) error)
	// episodeDescID is the schema descriptor for id field.
	episodeDescID := episodeFields[0].Descriptor()
	// episode.IDValidator is a validator for the "id" field. It is called by the builders before save.
	episode.IDValidator = episodeDescID.Validators[0].(func(string) error)
	profileFields := schema.Profile{}.Fields()
	_ = profileFields
	// profileDescCreatedAt is the schema descriptor for created_at field.
	profileDescCreatedAt := profileFields[1].Descriptor()
	// profile.DefaultCreatedAt holds the default value on creation for the created_at field.
	profile.DefaultCreatedAt = profileDescCreatedAt.Default.(func() time.Time)
	// profileDescUpdatedAt is the schema descriptor for updated_at field.
	profileDescUpdatedAt := profileFields[2].Descriptor()
	// profile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	profile.DefaultUpdatedAt = profileDescUpdatedAt.Default.(func() time.Time)
	// profileDescEmail is the schema descriptor for email field.
	profileDescEmail := profileFields[3].Descriptor()
	// profile.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	profile.EmailValidator = profileDescEmail.Validators[0].(func(string) error)
	// profileDescDisplayName is the schema descriptor for display_name field.
	profileDescDisplayName := profileFields[4].Descriptor()
	// profile.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	profile.DisplayNameValidator = profileDescDisplayName.Validators[0].(func(string) error)
	// profileDescPicture is the schema descriptor for picture field.
	profileDescPicture := profileFields[5].Descriptor()
	// profile.PictureValidator is a validator for the "picture" field. It is called by the builders before save.
	profile.PictureValidator = profileDescPicture.Validators[0].(func(string) error)
	// profileDescID is the schema descriptor for id field.
	profileDescID := profileFields[0].Descriptor()
	// profile.IDValidator is a validator for the "id" field. It is called by the builders before save.
	profile.IDValidator = profileDescID.Validators[0].(func(string) error)
	showFields := schema.Show{}.Fields()
	_ = showFields
	// showDescCreatedAt is the schema descriptor for created_at field.
	showDescCreatedAt := showFields[1].Descriptor()
	// show.DefaultCreatedAt holds the default value on creation for the created_at field.
	show.DefaultCreatedAt = showDescCreatedAt.Default.(func() time.Time)
	// showDescUpdatedAt is the schema descriptor for updated_at field.
	showDescUpdatedAt := showFields[2].Descriptor()
	// show.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	show.DefaultUpdatedAt = showDescUpdatedAt.Default.(func() time.Time)
	// showDescTitle is the schema descriptor for title field.
	showDescTitle := showFields[3].Descriptor()
	// show.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	show.TitleValidator = showDescTitle.Validators[0].(func(string) error)
	// showDescSummary is the schema descriptor for summary field.
	showDescSummary := showFields[4].Descriptor()
	// show.SummaryValidator is a validator for the "summary" field. It is called by the builders before save.
	show.SummaryValidator = showDescSummary.Validators[0].(func(string) error)
	// showDescPicture is the schema descriptor for picture field.
	showDescPicture := showFields[5].Descriptor()
	// show.PictureValidator is a validator for the "picture" field. It is called by the builders before save.
	show.PictureValidator = showDescPicture.Validators[0].(func(string) error)
	// showDescID is the schema descriptor for id field.
	showDescID := showFields[0].Descriptor()
	// show.IDValidator is a validator for the "id" field. It is called by the builders before save.
	show.IDValidator = showDescID.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[3].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[4].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(string) error)
}
