// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Episode is the predicate function for episode builders.
type Episode func(*sql.Selector)

// Profile is the predicate function for profile builders.
type Profile func(*sql.Selector)

// Show is the predicate function for show builders.
type Show func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
